# permissions for end users to view opconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opconfigmap-viewer-role
rules:
- apiGroups:
  - opconfigmap.example.com
  resources:
  - opconfigmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opconfigmap.example.com
  resources:
  - opconfigmaps/status
  verbs:
  - get
